# Change these first
owner: jflattery
repo: upptime

sites:
  - name: Baby
    url: $SECRET_SITE
  - name: HASS
    check: "tcp-ping"
    url: $HASS_SITE
    port: $HASS_PORT

status-website:
  baseUrl: /upptime
  name: Upptime
